# Generated by Django 6.0.5 on 2026-07-31 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Midi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('audio', models.FileField(upload_to='midis/audio/')),
                ('instruments', models.CharField(blank=True, default='', max_length=200)),
                ('midi', models.FileField(blank=True, null=True, upload_to='midis/midi/')),
                ('notes_json', models.TextField(blank=True, default='')),
                ('note_count', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
