# Generated by Django 6.0.5 on 2026-07-18 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackingTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backingtracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('audio_file', models.FileField(upload_to='stems/')),
                ('duration', models.FloatField(default=0)),
                ('backing_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='backingtracks.backingtrack')),
            ],
            options={
                'unique_together': {('backing_track', 'name')},
            },
        ),
    ]
