# Generated by Django 6.0.5 on 2026-07-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('backingtracks', '0004_playlist_description_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backingtrack',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backingtracks', to='accounts.genre'),
        ),
    ]
